### ISSUE TITLE
Missing UI.Popup

### ISSUE THREAD

**Issue by wmyers** [touchstonejs/touchstonejs-starter#15]
`UI.Popup` component appears to be missing in touchstonejs 0.3.0 (as per this app) and 0.3.2 (latest at this time).

This borks the app at the start because `home` view uses it. It works if I comment it out in the `home` JSX

**Comment by dcousens** [comment]
@wmyers are you sure?

https://github.com/touchstonejs/touchstonejs/blob/master/src/ui/index.js#L16

**Comment by dcousens** [comment]
Confirmed, this is fixed in master, but master is at `0.4.0`.  @JedWatson thoughts?

**Comment by dcousens** [comment]
Closing, as this has been fixed in master and in `touchstonejs`.
