### ISSUE TITLE
How to build with PhoneGap Build for Android

### ISSUE THREAD

**Issue by iamvdo** [touchstonejs/touchstonejs-starter#21]
Hi,
I know that you're writing docs and more, but can you provide a simple how-to to compile this app? For example using PhoneGap Build?
I'm not familiar with Cordova, and PhoneGap Build seems a great alternative to quickly get a result.

I don't know which files are required, so I tried to upload a .zip of the application, first `platforms/android` folder, then the root folder, but I failed.

Thanks in advance.
Keep up the good work on TouchstoneJS. ;)

**Comment by jossmac** [comment]
Cordova have a great, easy to follow, getting started guide here: https://cordova.apache.org/docs/en/4.0.0/guide_cli_index.md.html that walks you through app creation, then platform and plugin addition.

@dcousens you're probably the most well versed on PhoneGap Build and Android; care to weigh in on that?

**Comment by iamvdo** [comment]
Oh, I've just realized that Cordova has nothing to do with PhoneGap Build. So, to get an app from PhoneGap Build, you basically just have to copy `config.xml` in `www` folder and create a `.zip` file of `www` content. That's it, well the simplest use case. ;)

**Comment by dcousens** [comment]
@iamvdo correct, a phone gap build is very simple and it should just work :)
