### ISSUE TITLE
use of this.watch and this.context

### ISSUE THREAD

**Issue by chauthai** [touchstonejs/touchstonejs-starter#22]
Hi Jed,

I'm trying out your fine framework and got a bit stuck in the source code.
I can't figured out the use of "this.watch" in combination with "this.context". ReactJS documentation doesn't mention both of these features.

e.g in /src/js/views/list-simple.js line [83](https://github.com/touchstonejs/touchstonejs-starter/blob/master/src/js/views/list-simple.js#L83). 

May I ask you to elaborate the use of context and watch here?

**Comment by dcousens** [comment]
Hi @chauthai!

`this.context` is a ReactJS context field set by the parent component with `getChildContext` and `childContextTypes`.
It allows for passing context down several layers deep in the component hierarchy without unnecessarily passing props all the way through.

`this.watch` is a mixin from [`react-sentry`](https://github.com/dcousens/react-sentry) that we use to listen to events on compatible `EventEmitter`s,  it calls the necessary cleanup functions in `componentWillUnmount` to make the code less error prone.

**Comment by dcousens** [comment]
@chauthai please re-open if you need any clarifications.
