### ISSUE TITLE
New errors - Invariant Violation and toUpperCase on undefined

### ISSUE THREAD

**Issue by hollyschinsky** [touchstonejs/touchstonejs-starter#24]
I grabbed the latest update this week and now seeing these errors shown below when I run:

<img width="778" alt="screen shot 2015-08-03 at 4 30 58 pm" src="https://cloud.githubusercontent.com/assets/359935/9046998/c01d98b2-39fc-11e5-974d-77fd51724ff3.png">

**Comment by jossmac** [comment]
Thanks for catching this!
