### ISSUE TITLE
Transitions throw: Uncaught ReferenceError: clearImmediate is not defined

### ISSUE THREAD

**Issue by mbrookes** [touchstonejs/touchstonejs-starter#27]
Transitions work (to the "Hold on a sec..." view), fade back to the transitions view, then throw the error and immediately snap back to "Hold on a sec..."

At that point a reload is required to do anything else (i.e. tabs no longer function).

Versions:
```
mbrookes$ node -v
v0.12.7

mbrookes$ npm list --depth=0
touchstonejs-starter@0.0.2 /Users/mbrookes/Projects/touchstonejs-starter
├── async@1.4.1
├── classnames@2.1.3
├── cordova-dialogs@1.0.2
├── gulp@3.9.0
├── happiness@1.0.7
├── httpify@1.0.0
├── react@0.13.3
├── react-container@0.2.4
├── react-sentry@0.4.2
├── react-tappable@0.5.7
├── react-timers@3.4.1
├── touchstonejs@0.5.0
└── touchstonejs-tasks@0.3.1

mbrookes$ npm list -g --depth=0
/usr/local/lib
├── add-cors-to-couchdb@0.0.4
├── 
├── bower@1.4.0
├── coffee-script@1.8.0
├── cordova@4.3.0
├── grunt-cli@0.1.13
├── gulp@3.9.0
├── ionic@1.3.17
├── ios-sim@3.1.1
├── jasmine-node@1.14.5
├── less@2.1.1
├── npm@2.12.1
├── react@0.13.3
├── react-ui-builder@0.2.7
├── reapp@0.8.28
└── reapp-ui@0.12.54
```

I've tried a few browsers (Safari, Firefox, Chrome).

Any ideas?

Thanks.

**Comment by dcousens** [comment]
Hi @mbrookes,  I can only posit that this is coming from `react-timer`s again,  as I recently made some changes there by adding `setImmediate`,  however it should *never* be run non-explicitly,  so I'm not sure how you're experiencing this.

Reference for `3.4.1`: https://github.com/dcousens/react-timers/blob/3.x.y/src/index.js

**Comment by dcousens** [comment]
Still an issue.  Debugging...

**Comment by dcousens** [comment]
Resolved,  `setImmediate` has been removed,  wasn't aware it is literally supported by none of the browsers.

**Comment by mbrookes** [comment]
Thanks!
