### ISSUE TITLE
How to build touchstone-starter with Cordova?

### ISSUE THREAD

**Issue by nmiddleweek** [touchstonejs/touchstonejs-starter#28]
Hi,

I've just forked and then cloned my version of touchstonejs-starter - hope that was the correct procedure?

I then ran npm-install and npm-start and I can see the localhost:8000 nicely but I'm trying to workout if you have any CLI's to build it with Cordova?

Is that outside of the scope of this starter project and should I be looking to the https://cordova.apache.org/ docs or have you guys bundled something in a way that I believe http://reapp.io/docs-builds.html has?

Is there a better place for this type of question?

Cheers,
Nick

**Comment by jossmac** [comment]
Hi @nmiddleweek, Cordova docs is where you want to look

**Comment by nmiddleweek** [comment]
Cheers Joss!
