### ISSUE TITLE
Change caret to tilde in config.xml for Cordova issue

### ISSUE THREAD

**Issue by hollyschinsky** [touchstonejs/touchstonejs-starter#30]
Currently there's [a bug in Cordova](https://issues.apache.org/jira/browse/CB-9503) that will cause the plugin versions specified by the `spec` or `version` attribute in the **config.xml**  to fail to be added if they contain a caret(`^`). It also may not be obvious they were not actually installed based on the output received. You can change the caret to a tilde (`~`) to fix it, such as:

        <plugin name="cordova-plugin-device" spec="~1.0.0" />
        <plugin name="cordova-plugin-splashscreen" spec="~2.0.0" />
        <plugin name="cordova-plugin-statusbar" spec="~1.0.0" />
        <plugin name="cordova-plugin-whitelist" spec="~1.1.0" />

**Comment by dcousens** [comment]
Important to note that this is only a bug in the **latest** version of cordova, and will probably be resolved promptly.
The above solution is fine,  as is just using cordova `<5.1.1`.

Feel free to submit a pull request @hollyschinsky :+1: ,  but,  this doesn't really add much value IMHO.

**Comment by hollyschinsky** [comment]
Cool. I think it's worth documenting here at least in the meantime in case others run into it when getting started. :)

**Comment by JedWatson** [comment]
Thanks for the info @hollyschinsky - I've ended up pinning the versions because later versions of `cordova-plugin-whitelist` conflict with `cordova-ios`.

Also, great [blog post](http://devgirl.org/2015/09/22/sample-phonegap-app-with-reactjs/)! We really enjoyed it :grinning:
