### ISSUE TITLE
Update README to remove prepare task and add Cordova steps

### ISSUE THREAD

**Issue by hollyschinsky** [touchstonejs/touchstonejs-starter#31]
The `gulp prepare` task for cordova was removed in [touchstone-tasks v3.0.0](https://github.com/touchstonejs/touchstonejs-tasks/commits/v0.3.0), so it should be removed from the README to avoid confusion. 

Instead, you could guide developers to use the `cordova cli` commands to add a platform and build/run after the `gulp dev` task is run. 

Cordova steps 
1. `gulp dev`
2. `cordova platform add ios`
3. `cordova run ios`                    `// automatically runs cordova prepare  and build first`

**Note:** if [this plugin version issue](https://github.com/touchstonejs/touchstonejs-starter/issues/30) is not resolved, they will need to update their **config.xml** manually for the `cordova` commands above to install the plugin dependencies, otherwise they could see issues when running the starter project without them.

**Comment by dcousens** [comment]
@hollyschinsky you could probably submit this as a pull request!

**Comment by mgerlach-klick** [comment]
@hollyschinsky Thank you for that heads-up!

**Comment by JedWatson** [comment]
I rewrote the readme pretty comprehensively, let me know if you think it could use any more tweaks :)
