### ISSUE TITLE
Demo app is broken

### ISSUE THREAD

**Issue by timuric** [touchstonejs/touchstonejs-starter#33]
Seems like the touchstonejs-starter app is broken. After fresh clone of the project and successful npm install the app runs with glitches. Here is the console output http://d.pr/i/IlZu

**Comment by jrhicks** [comment]
Demo app depends on touchstonejs commits that haven't been released.  You can use the latest commits by:

Outside of your demo app, clone, build, and link the latest touchstonejs

* git clone https://github.com/touchstonejs/touchstonejs

* gulp build:lib

* sudo npm link 

Then from your touchstonejsjs-starter directory

* npm link touchstonejs

* gulp dev

**Comment by JedWatson** [comment]
Sorry about this - all fixed now.
