### ISSUE TITLE
Mix touchstone, react-router and react-bootstrap

### ISSUE THREAD

**Issue by pke** [touchstonejs/touchstonejs-starter#36]
I need deep linking in my Cordova app and would like to use react-router for that. Would that work with touchstonejs? Also could react-bootstrap and touchstonejs be mixed?

**Comment by veeramarni** [comment]
Any luck with it?

**Comment by gotoAndBliss** [comment]
Yah, any update? Im bout to embark on the same.

**Comment by pke** [comment]
Completely abandoned touchstone due to inactive development and created my own UX framework for iOS and Android

**Comment by jossmac** [comment]
Cool, do you have a link?

**Comment by pke** [comment]
Unfortunately its closed source. Will be opened up later maybe.
But basically its just a higher order component that decides based on the device OS how the CSS and flow on the pages should look like.
