### ISSUE TITLE
How to load store data in subview

### ISSUE THREAD

**Issue by heivin** [touchstonejs/touchstonejs-starter#39]
Seems like when it claim 

const peopleStore = new PeopleStore()

in app.js, it will make http request immediately, and used from cache in subview 

getInitialState () {
		return {
			searchString: '',
			people: this.context.peopleStore.getPeople()
		}
	},

So the question is how can i load store's data when it comes to the specific subview.

**Comment by dcousens** [comment]
This will entirely depend on your architecture.

Perhaps leave `PeopleStore` undefined until `componentDidMount` and only initialize it there?
To be honest though,  that is an anti-pattern,  and you should probably just stop `PeopleStore` from performing the request immediately and instead only when you need it.
