### ISSUE TITLE
meteor coughs

### ISSUE THREAD

**Issue by wiber** [touchstonejs/touchstonejs-starter#4]
Feel free to close this issue as it may not be relevant here. I'm looking into touchstone for a meteor project. Rather than tease out the parts there was a hope to just use npm but no:

Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
   node_modules/touchstonejs/site/public/index.html:1: Can't set DOCTYPE here.
   (Meteor sets <!DOCTYPE html> for you

also, meteor is going nuts because js files have html in them, perhaps jsx files would avoid this.

meteor --version
Meteor 1.0.2.1

**Comment by nkbt** [comment]
@wiber I reckon it is quite tricky to mate Meteor with anything except Meteor.

**Comment by wiber** [comment]
You're not wrong.. though I replaced doctype I couldn't figure out how to get less working properly, it expects a certain directory structure. Just npm packages work fine but I don't know enough to hook up the less paths.

**Comment by dcousens** [comment]
How'd you end up going with this?

**Comment by mbrookes** [comment]
Meteor now officially supports React, so it should be significantly easier, although the fact that TouchstoneJS has its own router which may not be Meteor friendly could be problematic.

**Comment by mbrookes** [comment]
Meteor now officially supports React, so it should be significantly easier, although the fact that TouchstoneJS has its own router which may not be Meteor friendly could be problematic. Otherwise it could be a match made in heaven.

**Comment by dcousens** [comment]
Thanks @mbrookes ,  I'm going to close this unless other issues come up.
