### ISSUE TITLE
How to use multiple httpify

### ISSUE THREAD

**Issue by sajumani** [touchstonejs/touchstonejs-starter#40]
Hi,

Am trying to use httpify( API services ), Somewhere i failed to include it with my app. I could not find anynotes on React Js tutorial too.

Could you help me out ...???

**Comment by dcousens** [comment]
Are you looking for https://github.com/scottcorgan/httpify?

**Comment by sajumani** [comment]
Yes, that am integrate with touchStoneJs but i failed to use multiple httpify services,

Note : This is product App 

i want to show category with one httpify service, one for products from that category


both i will get from different httpify.... Could you give clear instructions with TouchstoneJs note

**Comment by dcousens** [comment]
@sajumani I don't understand what you're asking, sorry.

**Comment by sajumani** [comment]
Am integrating  product App with touchStoneJs but i failed to use multiple httpify services in single component...

Note : This is product App

i want to show category with one httpify service, one for products from that category

both i will get from different httpify.... Could you give clear instructions with TouchstoneJs note

**Comment by dcousens** [comment]
> use multiple httpify services

Do you mean you failed to use `httpify({ ... })`, the function, more than once?
What does `failed` mean?  Do you get an error?

> Note : This is product App
>i want to show category with one httpify service, one for products from that category
> ... blah blah

You already said that.

**Comment by sajumani** [comment]
Yes, am trying to httpify(), more than once...
Failed means , i could not get second service data with synchronize action...

actually we are new to Touchstonejs, we referred this to our client but we could not get clear notes to build app.... so am trying to customize touchstone starter ....

**Comment by sajumani** [comment]
how do i call httpify after transition change...?? within the render can i call httpify..??

**Comment by dcousens** [comment]
> within the render can I call httpify

@sajumani I think you should do some [react tutorials](https://duckduckgo.com/?q=react+tutorials).
This is out of the scope of `touchstonejs-starter`, which lightly assumes you have at least some knowledge of `react` life cycles and patterns.

In answer to your question, no you would not call `httpify` in `render`, as it is a pure function (stateless, with no side effects).

> how do i call httpify after transition change

Call `httpify` in `componentDidMount`, with a subsequent `setState` in the callback.  Its not great, but, it'll work.
