### ISSUE TITLE
Missing new react library for css transitions (was split out)

### ISSUE THREAD

**Issue by brainlid** [touchstonejs/touchstonejs-starter#44]
**Reproduction steps:**

Starting with a clean download, run the following...

```
npm install
npm start
```

Error in gulp...

```
[21:01:16] Finished 'fonts' after 2.27 s
[21:01:17] Browserify Error:
           Cannot find module 'react-addons-css-transition-group' from '/home/mark/dev/cordova/touchstonejs-starter-master'
[21:01:20] Finished 'images' after 5.51 s
```

To fix this issue
```
npm install --save react-addons-css-transition-group
```

It adds the following to package.json

```
"react-addons-css-transition-group": "^0.14.3",
```

**Comment by JedWatson** [comment]
@brainlid sorry about that - npm had flattened that dependency for me from touchstonejs so it didn't notice it was missing from this package.json

thanks for the catch!
