### ISSUE TITLE
Content-Security-Policy issue

### ISSUE THREAD

**Issue by robreiss** [touchstonejs/touchstonejs-starter#49]
I believe the current Content-Security-Policy in index.html is not working as intended.

Current code:
```
<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: script-src style-src 'self' 'unsafe-inline'; media-src *">
```
There are some missing semicolons in between the "default-src", "script-src", "style-src".
In addition to fixing the typos I believe you will need to whitelist the domain randomuser.me to see results in the "Simple List" and "Complex List"
You may also wish to whitelist localhost:35729 while debugging to continue to have livereload work correctly.

The simplest solution is to open up the security completely:
```
<meta http-equiv="Content-Security-Policy" >
```
If you want a tighter security policy it might look something like the following (I haven't tested this on all platforms):
```
<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-inline' http://localhost:35729; connect-src  https://*.randomuser.me http://*.randomuser.me ws://localhost:35729; img-src 'self' https://*.randomuser.me http://*.randomuser.me; ">
```

**Comment by JedWatson** [comment]
Thanks for the fix suggestions @robreiss! I've opened it up somewhere between your two suggestions; I don't think there's really any concern with doing so because it's intended as a "boilerplate" project anyway, but let me know if you think I should change it any further.
